### ISSUE TITLE
Real sendall for HTTPS requests not working

### ISSUE THREAD

**Issue by dustinfarris** [mindflayer/python-mocket#62]
I am using Python 3.6.4 and getting this error when I try to use mocket:

```
E           http.client.BadStatusLine: 2

/usr/local/Cellar/python3/3.6.4_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py:279: BadStatusLine
```

**Comment by mindflayer** [comment]
Hi @dustinfarris, could you please be more specific?
What are you trying to do?
Or better, are you able to create a snippet where `mocket` crashes in that way?

**Comment by mindflayer** [comment]
So, I've just tried to run the test suite with Python 3.6.4 and it succeeded. I definitely need more information. :)

**Comment by mindflayer** [comment]
Are you able to write a small snippet which makes it fail? If so I will add it as test and start working maybe even tonight/tomorrow.

**Comment by dustinfarris** [comment]
This isn't a bug actually, sorry.  See #63 for an explanation.

**Comment by mindflayer** [comment]
Now that I see it, the problem is much more clear and I am already aware about it. It is definitely a bug, because `Mocket` should call the real `sendall` and do the job for you every time there is a connection which you don't want to mock.
Basically, SSL sockets are not working like we expect, and I am trying to fix it on this branch:
https://github.com/mindflayer/python-mocket/tree/ssl-fix
