### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by clintonb** [mindflayer/python-mocket#9]
You link to a 37 minute long video. While the video may hold useful information, few will spend time viewing it.

**Comment by saksham-kumar** [comment]
The explanation is not clear. 
"for all kinds of socket animals, web-clients included - with gevent/asyncio/SSL support"
doesn't explain what mocket does.

**Comment by mindflayer** [comment]
Hi @saksham-kumar, there are a couple of blog posts I've written recently that should help:
https://medium.com/@mindflayer/mocket-is-alive-and-is-fighting-with-us-b2810d52597a
https://hackernoon.com/make-development-great-again-faab769d264e#.pokdigch1

The README published here should also help.

**Comment by mindflayer** [comment]
First of all, I am not against reopening the issue. The fact that an issue is open does not imply that the related problem gets solved.

> I like the enthusiastic tone of the many articles linked from the README, but most of them are from 2017 and the latest one is three years old. 

Mocket has NEVER changed its interfaces. So, the fact that the articles are old is kinda irrelevant. I used the example from one of the articles months ago to present Mocket to some colleagues and all went fine.

> This situation probably also means documenting could even be delegated to outside contributors.

There are no outside contributors, unfortunately. The only PRs that I received, in case they shipped code, were to solve specific problems people were experiencing.

> Because of this I think there should be a large number of documentation-expecting users

My perception is quite different though, I co-authored Mocket in 2013 and I've been the only maintainer for ages. Many people don't use Mocket because today there are simpler alternatives. With simpler I don't mean they have simpler APIs, I mean the way they work is closer to the way people normally mock their code ([unittest.mock](https://docs.python.org/3/library/unittest.mock.html). Back in the day, when `httpretty` was born, it was the only alternative available. It became very famous because of that, and I am sorry but the project was never well-kept (e.g. Python 3 support arrived late and incomplete).

> I judge it to have a visibility problem, which I expect could be ameliorated with (more) accessible documentation.

Same thing here, you assume many people need Mocket while the reality is different. People want to use simple client-side mocking techniques. Mocket is the only alternative if you are developing a client for a new protocol, or something like that. For mocking a few API calls there are simpler solutions. Of course, they way Mocket works make your tests more reliable, but this is not something that many people care nor understand.

This said. If you are offering to contribute to the project with documentation, feel free to do it. I'll reopen the issue if this makes you happier. But I am sorry I have no time to invest in writing more documentation, considering that all use-cases are covered by meaningful examples. The internals of Mocket don't interest to many people.

**Comment by mindflayer** [comment]
I forgot to mention that recently I added to the README a button pointing to DeepWiki, platform which generates documentation through LLMs. You may want to dig into it first.
